# Generated by Django 5.2.7 on 2025-11-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_mahasiswa/'),
        ),
    ]
