# Generated by Django 5.2.7 on 2025-11-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_mahasiswa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mahasiswa/'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
