# Generated by Django 5.2.7 on 2025-11-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_mahasiswa_foto_alter_mahasiswa_nim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('penulis', models.CharField(default='Admin', max_length=100)),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
            },
        ),
    ]
