# Generated by Django 5.2.7 on 2025-11-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_pengumuman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilai',
            name='matakuliah',
        ),
        migrations.AddField(
            model_name='nilai',
            name='mata_kuliah',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nilai',
            name='sks',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nilai',
            field=models.FloatField(),
        ),
    ]
