# Generated by Django 5.2.7 on 2025-11-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_remove_nilai_matakuliah_nilai_mata_kuliah_nilai_sks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matakuliah',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nilai',
            options={},
        ),
        migrations.RenameField(
            model_name='matakuliah',
            old_name='nama_mk',
            new_name='nama_matkul',
        ),
        migrations.RemoveField(
            model_name='matakuliah',
            name='kode_mk',
        ),
        migrations.RemoveField(
            model_name='nilai',
            name='sks',
        ),
        migrations.AlterField(
            model_name='nilai',
            name='mata_kuliah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.matakuliah'),
        ),
    ]
