# Generated by Django 5.2.7 on 2025-11-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_matakuliah_options_alter_nilai_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nilai',
            options={'verbose_name': 'Nilai', 'verbose_name_plural': 'Nilai'},
        ),
        migrations.AddField(
            model_name='nilai',
            name='sks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='mata_kuliah',
            field=models.CharField(default='Tidak Diketahui', max_length=100),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nilai',
            field=models.FloatField(default=0),
        ),
    ]
