# Generated by Django 5.2.7 on 2025-11-03 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_nilai_options_nilai_sks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matakuliah',
            options={'verbose_name': 'Mata Kuliah', 'verbose_name_plural': 'Mata Kuliah'},
        ),
        migrations.RenameField(
            model_name='matakuliah',
            old_name='nama_matkul',
            new_name='nama_mk',
        ),
        migrations.RemoveField(
            model_name='nilai',
            name='sks',
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='kode_mk',
            field=models.CharField(default='MK001', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nilai',
            name='mata_kuliah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.matakuliah'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nilai',
            field=models.FloatField(),
        ),
    ]
