# Generated by Django 5.2.7 on 2025-11-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_matakuliah_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='kode_mk',
            field=models.CharField(max_length=10),
        ),
    ]
