# Generated by Django 5.2.7 on 2025-11-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_matakuliah_kode_mk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nilai',
            options={},
        ),
        migrations.AddField(
            model_name='nilai',
            name='sks',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nilai',
            name='mata_kuliah',
            field=models.CharField(max_length=100),
        ),
    ]
