# Generated by Django 5.2.7 on 2025-11-03 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_alter_nilai_options_nilai_sks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nilai',
            options={'verbose_name': 'Nilai', 'verbose_name_plural': 'Nilai'},
        ),
        migrations.RemoveField(
            model_name='nilai',
            name='sks',
        ),
        migrations.AlterField(
            model_name='nilai',
            name='mata_kuliah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.matakuliah'),
        ),
    ]
