# Generated by Django 5.2.7 on 2025-11-03 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_nilai_options_remove_nilai_sks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tagihan', models.CharField(max_length=100)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], max_length=50)),
                ('tanggal', models.DateField()),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.mahasiswa')),
            ],
        ),
    ]
