# Generated by Django 5.2.7 on 2025-11-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_tagihan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagihan',
            name='status',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=20),
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
