# Generated by Django 5.2.7 on 2025-11-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_alter_tagihan_status_alter_tagihan_tanggal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagihan',
            options={'verbose_name': 'Tagihan', 'verbose_name_plural': 'Tagihan'},
        ),
    ]
