# Generated by Django 5.2.7 on 2025-11-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_alter_tagihan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
